version: "3"
networks:
  default:
services:
  # PHP
  php:
    build:
      context: ./services/php/
    container_name: php
    depends_on:
      - mysql
      - redis
    expose:
      - 9000
    volumes:
      - ./www/:/var/www/:rw
      - ./services/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./services/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./logs/php/:/var/log/php/
      - ./data/composer/:/tmp/composer/
    restart: always
    links:
      - mysql
      - redis
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  # Nginx
  nginx:
    image: nginx:1.18.0
    container_name: nginx
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ : "Asia/Shanghai"
    volumes:
      - ./www:/var/www:rw
      - ./services/nginx/ssl:/ssl:ro
      - ./services/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./services/nginx/fastcgi-php.conf:/etc/nginx/fastcgi-php.conf:ro
      - ./services/nginx/fastcgi_params:/etc/nginx/fastcgi_params:ro
      - ./logs/nginx/:/var/log/nginx/:rw
    restart: always
    links:
      - php
    networks:
      - default

  # MySQL
  mysql:
    image: mysql:8.0.20
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./services/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./data/mysql/:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "123123"
      TZ: "Asia/Shanghai"

  # Redis
  redis:
    image: redis:6.0.5
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./services/redis/redis.conf:/etc/redis.conf:ro
      - ./data/redis:/data/:rw
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    environment:
       TZ: "Asia/Shanghai"
    networks:
      - default

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3.8.4-management
    container_name: rabbitmq
    hostname: my-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq/:/var/lib/rabbitmq/:rw
      - ./services/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    restart: always
    networks:
      - default
    environment:
      TZ: "Asia/Shanghai"
